
import = [
    # "~/.config/alacritty/themes/snazzy.toml"
    # "~/.config/alacritty/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/themes/gruvbox_material_dark.toml"
    "~/.config/alacritty/themes/cloud.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1
blur = true

option_as_alt = "Both"

[font]
# normal.family = "MesloLGS Nerd Font Mono"
normal.family = "JetBrainsMono Nerd Font"

size = 18

[keyboard]
bindings = [
  # { key = "C", mods = "Control|Shift", mode = "Vi|Search", action = "ClearSelection" },
  # { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Right", mods = "Alt",        chars = "\u001BF" }, # jump word 
  { key = "Left",  mods = "Alt",        chars = "\u001BB" }, # jump word backwords
  { key = "a",     mods = "Control",    chars = "\u0001"  }, # jump start of line
  { key= "Key0",   mods=  "Control",    chars = "\u0005"  },  # jump end of line
]

